[project]
name = "monitor-bulletproof"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.asset-registry]
path = "contracts/asset-registry.clar"
depends_on = []

[contracts.monitoring-service]
path = "contracts/monitoring-service.clar"
depends_on = []

[contracts.bulletproof-token]
path = "contracts/bulletproof-token.clar"
depends_on = []

[contracts.monitoring-trading]
path = "contracts/monitoring-trading.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
